import './styles.css';
import { lessons, finalQuestions } from './course.js';
import { courseApi, isSupabaseConfigured } from './supabase.js';
const app=document.querySelector('#app'),storeKey='frazeokvest-students-demo';
const saved=JSON.parse(localStorage.getItem(storeKey)||'null');
const state=saved||{screen:'auth',mode:'login',name:'Студент',email:'student@example.com',role:'student',completed:[],scores:{},final:null,certificate:null,current:1};
const save=()=>localStorage.setItem(storeKey,JSON.stringify(state));
const logo=()=>`<div class="brand"><div class="brand-mark">Ф</div><span>Фразеология</span></div>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function shell(content,active='course'){return `<div class="app-shell"><header class="topbar">${logo()}<div class="user"><div class="avatar">${esc(state.name[0]||'С')}</div><span><strong>${esc(state.name)}</strong><br><small>${state.role==='admin'?'Преподаватель':'Студенческий курс'}</small></span></div></header><div class="workspace"><nav class="sidebar"><small>ОБУЧЕНИЕ</small><button data-go="course" class="${active==='course'?'active':''}">Мой курс</button><button data-go="final" class="${active==='final'?'active':''}">Итоговый тест</button><button data-go="certificate" class="${active==='certificate'?'active':''}">Сертификат</button>${state.role==='admin'||!isSupabaseConfigured?`<small>УПРАВЛЕНИЕ</small><button data-go="admin" class="${active==='admin'?'active':''}">Админ-панель</button>`:''}<button data-action="logout">Выйти</button></nav><main class="content">${content}</main></div></div>`}
function renderAuth(message=''){app.innerHTML=`<main class="auth-wrap"><section class="auth-card">${logo()}<span class="eyebrow">Массовый онлайн-курс</span><h1>${state.mode==='register'?'Создать аккаунт':'Войти в курс'}</h1><p class="muted">15 тем: материал → мини-тест. После них — итоговый тест по всему курсу.</p>${message?`<div class="notice">${esc(message)}</div>`:!isSupabaseConfigured?'<div class="notice">Supabase пока не настроен — доступен локальный демо-режим.</div>':''}<form data-form="auth">${state.mode==='register'?'<label class="field">ФИО<input name="name" required placeholder="Иванов Иван Иванович"></label>':''}<label class="field">Email<input name="email" type="email" required placeholder="student@example.com"></label><label class="field">Пароль<input name="password" type="password" required minlength="6" placeholder="••••••••"></label><button class="btn btn-primary" type="submit">${state.mode==='register'?'Зарегистрироваться':'Войти'}</button></form><button class="link-btn" data-action="toggle-auth">${state.mode==='register'?'Уже есть аккаунт? Войти':'Нет аккаунта? Регистрация'}</button>${!isSupabaseConfigured?'<button class="btn btn-outline demo" data-action="demo">Открыть демо курса</button>':''}</section></main>`}
function dashboard(){const done=state.completed.length,percent=Math.round(done/15*100);const cards=lessons.map((l,i)=>{const locked=i>done,passed=state.completed.includes(l.id);return `<button class="lesson-card" data-lesson="${l.id}" ${locked?'disabled':''}><span class="lesson-no">${passed?'✓':l.id}</span><h3>${l.title}</h3><p>${l.summary}</p><span class="status">${passed?`Пройдено · ${state.scores[l.id]}%`:i===done?'Изучить материал':'Откроется после предыдущей темы'}</span></button>`}).join('');app.innerHTML=shell(`<section class="hero"><span class="eyebrow">Фразеология русского языка</span><h1>Последовательный курс для студентов</h1><p>Сначала изучите материал, затем сдайте мини-тест. Следующая лекция откроется автоматически.</p><div class="progress-row"><span>Прогресс курса</span><span>${done} / 15</span></div><div class="progress"><i style="width:${percent}%"></i></div></section><div class="section-head"><div><span class="eyebrow">Учебный план</span><h2>15 лекций</h2></div></div><section class="lesson-list">${cards}</section><button class="final-card ${done<15?'locked':''}" data-go="final" ${done<15?'disabled':''}><span class="eyebrow">Финальный этап</span><h2>Итоговый тест по всем темам</h2><p>${done<15?'Откроется после успешной сдачи всех мини-тестов.':'Все темы пройдены — можно начинать итоговую проверку.'}</p></button>`,'course')}
function lessonView(id){const l=lessons[id-1];state.current=id;save();app.innerHTML=shell(`<button class="back" data-go="course">← К списку лекций</button><article class="article"><span class="eyebrow">Лекция ${l.id} из 15</span><h1>${l.title}</h1><p class="lead">${l.summary}</p>${l.sections.map(s=>`<section><h2>${s.title}</h2><p>${s.text}</p></section>`).join('')}<aside><strong>Главное:</strong> сначала определите целостное значение, затем оцените форму, образ и контекст.</aside><button class="btn btn-primary" data-action="start-quiz">Перейти к мини-тесту</button></article>`,'course')}
function questionsHtml(qs){return qs.map((q,i)=>`<fieldset><legend>${i+1}. ${q.question}</legend>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" required><span>${o}</span></label>`).join('')}</fieldset>`).join('')}
function quizView(){const l=lessons[state.current-1];app.innerHTML=shell(`<button class="back" data-lesson="${l.id}">← Вернуться к материалу</button><section class="test-card"><span class="eyebrow">Мини-тест · Лекция ${l.id}</span><h1>${l.title}</h1><p class="muted">Для прохождения нужно ответить верно минимум на 2 из 3 вопросов.</p><form data-form="quiz">${questionsHtml(l.quiz)}<button class="btn btn-primary" type="submit">Проверить ответы</button></form></section>`,'course')}
function resultView(score,passed){app.innerHTML=shell(`<section class="result ${passed?'success':'fail'}"><div class="result-icon">${passed?'✓':'!'}</div><span class="eyebrow">Результат мини-теста</span><h1>${score}%</h1><p>${passed?'Тема усвоена. Следующая лекция открыта.':'Нужно не менее 67%. Повторите материал и попробуйте снова.'}</p><div class="actions"><button class="btn btn-primary" data-go="course">К учебному плану</button><button class="btn btn-outline" data-lesson="${state.current}">Повторить материал</button></div></section>`,'course')}
function finalView(){if(state.completed.length<15){app.innerHTML=shell(`<section class="empty"><h1>Итоговый тест пока закрыт</h1><p>Сначала пройдите все 15 лекций и мини-тестов.</p><button class="btn btn-primary" data-go="course">Продолжить обучение</button></section>`,'final');return}app.innerHTML=shell(`<section class="test-card"><span class="eyebrow">Финальная проверка</span><h1>Итоговый тест по 15 темам</h1><p class="muted">15 вопросов. Для получения сертификата нужно набрать не менее 70%.</p><form data-form="final">${questionsHtml(finalQuestions)}<button class="btn btn-primary" type="submit">Завершить тест</button></form></section>`,'final')}
function certificateView(){if(!state.certificate){app.innerHTML=shell(`<section class="empty"><h1>Сертификат ещё не выдан</h1><p>Он появится после успешной сдачи итогового теста.</p><button class="btn btn-primary" data-go="course">Вернуться к курсу</button></section>`,'certificate');return}app.innerHTML=shell(`<section class="certificate" id="certificate"><div class="cert-logo">Ф</div><span>МАССОВЫЙ ОНЛАЙН-КУРС</span><h1>Сертификат</h1><p>подтверждает, что</p><h2>${esc(state.name)}</h2><p>успешно завершил(а) курс<br><strong>«Фразеология русского языка»</strong></p><div class="cert-meta"><span>Уровень<br><strong>Студенческий · High level</strong></span><span>Дата<br><strong>${state.certificate.date}</strong></span><span>№ сертификата<br><strong>${state.certificate.number}</strong></span></div></section><button class="btn btn-primary print" data-action="print">Скачать / печать</button>`,'certificate')}
async function adminView(search=''){let rows=[{full_name:state.name,email:state.email,completed:state.completed.length,final_score:state.final,certificate_number:state.certificate?.number}];if(isSupabaseConfigured){if(state.role!=='admin'){go('course');return}const response=await courseApi.adminSearch(search);rows=response.error?[]:(response.data||[])}const body=rows.map(r=>`<tr><td>${esc(r.full_name)}</td><td>${esc(r.email)}</td><td>${r.completed}/15</td><td>${r.final_score?r.final_score+'%':'—'}</td><td>${r.certificate_number||'—'}</td></tr>`).join('')||'<tr><td colspan="5">Ничего не найдено</td></tr>';app.innerHTML=shell(`<section class="admin-head"><span class="eyebrow">Панель преподавателя</span><h1>Учащиеся и результаты</h1><p>Поиск по ФИО, email или пятизначному номеру сертификата.</p><form data-form="admin-search"><input name="search" class="search" value="${esc(search)}" placeholder="Поиск..."><button class="btn btn-primary">Найти</button></form></section><div class="table-wrap"><table><thead><tr><th>ФИО</th><th>Email</th><th>Прогресс</th><th>Итоговый тест</th><th>Сертификат</th></tr></thead><tbody>${body}</tbody></table></div><p class="muted small">Данные доступны только пользователю с ролью admin.</p>`,'admin')}
function grade(form,questions){const data=new FormData(form);let correct=0;questions.forEach((q,i)=>{if(Number(data.get(`q${i}`))===q.correct)correct++});return Math.round(correct/questions.length*100)}
function go(screen){state.screen=screen;save();({course:dashboard,final:finalView,certificate:certificateView,admin:adminView}[screen]||dashboard)()}
app.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.action==='demo'){state.screen='course';save();dashboard()}if(el.dataset.action==='toggle-auth'){state.mode=state.mode==='login'?'register':'login';renderAuth()}if(el.dataset.action==='logout'){if(isSupabaseConfigured)await courseApi.logout();state.screen='auth';save();renderAuth()}if(el.dataset.action==='start-quiz')quizView();if(el.dataset.action==='print')window.print();if(el.dataset.go)go(el.dataset.go);if(el.dataset.lesson)lessonView(Number(el.dataset.lesson))});
app.addEventListener('submit',async e=>{e.preventDefault();const form=e.target;if(form.dataset.form==='auth'){const d=new FormData(form),name=d.get('name')||state.name,email=d.get('email'),password=d.get('password');if(isSupabaseConfigured){const response=state.mode==='register'?await courseApi.register(name,email,password):await courseApi.login(email,password);if(response.error){renderAuth(response.error.message);return}await hydrateRemote()}state.name=name;state.email=email;state.screen='course';save();dashboard()}if(form.dataset.form==='quiz'){const l=lessons[state.current-1],answers=l.quiz.map((_,i)=>Number(new FormData(form).get(`q${i}`)));let score=grade(form,l.quiz),passed=score>=67;if(isSupabaseConfigured){const {data,error}=await courseApi.submitLesson(l.id,answers);if(error){resultView(0,false);return}score=data.score;passed=data.passed}state.scores[l.id]=Math.max(state.scores[l.id]||0,score);if(passed&&!state.completed.includes(l.id))state.completed.push(l.id);save();resultView(score,passed)}if(form.dataset.form==='final'){const answers=finalQuestions.map((_,i)=>Number(new FormData(form).get(`q${i}`)));let score=grade(form,finalQuestions),passed=score>=70,number;if(isSupabaseConfigured){const {data,error}=await courseApi.submitFinal(answers);if(error)return;score=data.score;passed=data.passed;number=data.certificate}state.final=Math.max(state.final||0,score);if(passed&&!state.certificate)state.certificate={number:number||String(Math.floor(10000+Math.random()*90000)),date:new Date().toLocaleDateString('ru-RU')};save();if(passed)certificateView();else app.innerHTML=shell(`<section class="result fail"><div class="result-icon">!</div><h1>${score}%</h1><p>Для сертификата нужно не менее 70%. Повторите темы и попробуйте ещё раз.</p><button class="btn btn-primary" data-go="final">Пройти ещё раз</button></section>`,'final')}});
async function hydrateRemote(){const {data}=await courseApi.state();if(!data)return;state.name=data.profile?.full_name||state.name;state.email=data.profile?.email||state.email;state.role=data.profile?.role||'student';state.completed=(data.lessons||[]).filter(x=>x.passed).map(x=>x.lesson_id);state.scores=Object.fromEntries((data.lessons||[]).map(x=>[x.lesson_id,x.best_score]));state.final=data.final?.best_score||null;if(data.certificate)state.certificate={number:data.certificate.number,date:new Date(data.certificate.issued_at).toLocaleDateString('ru-RU')};save()}
async function bootstrap(){if(isSupabaseConfigured){const {data}=await courseApi.session();if(data.session){await hydrateRemote();state.screen='course';dashboard();return}state.screen='auth'}state.screen==='auth'?renderAuth():go(state.screen)}bootstrap();
